export { notificationData }

const notificationData = [
	{
		name: "Anna Kim",
		avatar: "./assets/images/avatar-anna-kim.webp",
		action: "left the group",
		regarding: "Chess Club",
		pictureSnippet: "",
		message: "",
		timeStamp: "2 weeks ago",
		unread: false,
	},
	{
		name: "Nathan Peterson",
		avatar: "./assets/images/avatar-nathan-peterson.webp",
		action: "reacted to your recent post",
		regarding: "5 end-game strategies to increase your win rate",
		pictureSnippet: "",
		message: "",
		timeStamp: "2 weeks ago",
		unread: false,
	},
	{
		name: "Kimberly Smith",
		avatar: "./assets/images/avatar-kimberly-smith.webp",
		action: "commented on your picture",
		regarding: "",
		pictureSnippet: "./assets/images/image-chess.webp",
		message: "",
		timeStamp: "1 week ago",
		unread: false,
	},
	{
		name: "Rizky Hasanuddin",
		avatar: "./assets/images/avatar-rizky-hasanuddin.webp",
		action: "sent you a private message",
		regarding: "",
		pictureSnippet: "",
		message:
			"Hello, thanks for setting up the Chess Club. I’ve been a member for a few weeks now and I’m already having lots of fun and improving my game.",
		timeStamp: "5 days ago",
		unread: false,
	},
	{
		name: "Jacob Thompson",
		avatar: "./assets/images/avatar-jacob-thompson.webp",
		action: "has joined your group",
		regarding: "Chess Club",
		pictureSnippet: "",
		message: "",
		timeStamp: "1 day ago",
		unread: true,
	},
	{
		name: "Angela Gray",
		avatar: "./assets/images/avatar-angela-gray.webp",
		action: "followed you",
		regarding: "",
		pictureSnippet: "",
		message: "",
		timeStamp: "5m ago",
		unread: true,
	},
	{
		name: "Mark Weber",
		avatar: "./assets/images/avatar-mark-webber.webp",
		action: "reacted to your recent post",
		regarding: "My first tournament today!",
		pictureSnippet: "",
		message: "",
		timeStamp: "1m ago",
		unread: true,
	},
]
